name: workflow.yml
on: push


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install dependencies
        run: |
          node -v
          npm -v
          node --version
