name: workflow.yml
on: push


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0

      - name: install dependencies
        run: |
          node -v
          npm -v
          npm ci
      - name: run tests
        run: npm test
      - name: Build application
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build
