name: workflow.yml
on: push


jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      js-file: ${{ steps.publish-js.outputs.file-name }}
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0

      - name: install dependencies
        run: |
          node -v
          npm -v
          npm ci
      - name: run tests
        run: npm test
      - name: Build application
        run: npm run build
      - name: publish js filename
        id: publish-js
        run:  find dist/assets/*.js -type f -execdir echo "file-name={}" >> "$GITHUB_ENV" ';'
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Download artifact
          uses: actions/download-artifact@v5
          with:
            name: app
        - name: list
          run: ls -la
        - name: published-file
          run: echo "published file is ${{ needs.test.outputs.js-file }}"
